GPUS: (0,)
WORKERS: 15
Loss: BCELoss
MODEL:
  NAME: 'FR_UNet'
  PRETRAINED: ''
TRAIN:
  BATCH_SIZE_PER_GPU: 9
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 500
  EARLY_STOP: 30
  OPTIMIZER: 'adam'
  LR: 0.0003
  WD: 0.0
  LR_STEP: [30, 50]
  MOMENTUM: 0.0
  NESTEROV: false